name: Reporte Stock Cocina

on:
  schedule:
    - cron: '0 12 * * *'  # 8am Chile (UTC-3)
  workflow_dispatch:

jobs:
  reporte:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar librerias
        run: pip install requests openpyxl

      - name: Crear config.txt
        run: |
          echo "BSALE_TOKEN = ${{ secrets.BSALE_TOKEN }}" > config.txt
          echo "GMAIL_REMITENTE = ${{ secrets.GMAIL_REMITENTE }}" >> config.txt
          echo "GMAIL_PASSWORD = ${{ secrets.GMAIL_PASSWORD }}" >> config.txt
          echo "CORREOS_DESTINO = ${{ secrets.CORREOS_DESTINO }}" >> config.txt
          echo "RUTA_EXCEL = cocina_STOCK_NUEVA.xlsx" >> config.txt
      - name: Ejecutar script
        env:
          BSALE_TOKEN: ${{ secrets.BSALE_TOKEN }}
          GMAIL_REMITENTE: ${{ secrets.GMAIL_REMITENTE }}
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
          CORREOS_DESTINO: ${{ secrets.CORREOS_DESTINO }}
        run: python bsale_github.py
